### ISSUE TITLE
I can't authenticate.

### ISSUE THREAD

**Issue by Alb4tr02** [abhaysbharadwaj/RFID-MRC522#1]
How do you authenticate a sector using the function auth?
Do you have an example?

**Comment by Toews8612** [comment]
Same question. The software SPI option is excellent but I'm unable to execute other functions in the library such as auth and read. Extending the example .ino to cover these would be awesome!

**Comment by abhaysbharadwaj** [comment]
Hello,
This was a very old library forked from Miguelbalboa's RC522 library long back and added software SPI functionality.
I tested this library only for read function for a project. It's been more than 4 years and I haven't worked with RC522 again.
Feel free to reuse and work it out. But I don't think I will be doing any further developments on this.

**Comment by Toews8612** [comment]
I sure appreciate you taking the time to reply Abhay ... very classy. I was able to work out an alternative solution.  All good on my end. Hope you and your family are safe and healthy. Thanks again.
